language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    IFS=',' read -ra IMAGE_ARRAY <<< "$IMAGE_NAMES"
    for IMAGE_NAME in "${IMAGE_ARRAY[@]}"; do
      IMAGE_FULL_NAME="$NAMESPACE/$IMAGE_NAME:latest"
      echo "Processing image: $IMAGE_FULL_NAME"

      # Pull the latest version of the image
      docker pull $IMAGE_FULL_NAME

      # Get the current image ID
      CURRENT_ID=$(docker inspect --format '{{.Id}}' $IMAGE_FULL_NAME)

      # Build the new version of the image
      docker build -t $IMAGE_FULL_NAME ./$IMAGE_NAME

      # Get the new image ID
      NEW_ID=$(docker inspect --format '{{.Id}}' $IMAGE_FULL_NAME)

      # Compare the image IDs
      if [ "$CURRENT_ID" == "$NEW_ID" ]; then
          echo "Image ID has not changed."
      else
          echo "Image ID has been updated from $CURRENT_ID to $NEW_ID."
          docker push $IMAGE_FULL_NAME
      fi
    done
